excluded: 
  - Pods

line_length:
  warning: 180
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

identifier_name:
  min_length: 2

type_name:
  min_length: 2
